# Generated by Django 4.2.23 on 2025-07-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('Array', 'Array'), ('Linked List', 'Linked List'), ('Tree', 'Tree'), ('Graph', 'Graph')], default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='example_input',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='problem',
            name='example_output',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(default=' '),
        ),
    ]
