# Generated by Django 4.2.23 on 2025-07-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(default=False, help_text='Check if the question is selected for interview session.')),
                ('question_type', models.CharField(choices=[('CODING', 'Coding'), ('LLD', 'Low Level Design')], default='CODING', help_text='Choose if the question is a coding problem or a low-level design question.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
